CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Idempotent upgrades for databases created before auth.
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS system_role VARCHAR(32) NOT NULL DEFAULT 'USER';
ALTER TABLE users ADD COLUMN IF NOT EXISTS settings JSONB;

CREATE TABLE IF NOT EXISTS auth_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_user ON auth_tokens (user_id);

CREATE TABLE IF NOT EXISTS stories (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    story_type       VARCHAR(32) NOT NULL,
    default_language VARCHAR(16) NOT NULL DEFAULT 'en',
    synopsis         TEXT,
    settings         JSONB,
    created_by       BIGINT NOT NULL REFERENCES users(id),
    updated_by       BIGINT NOT NULL REFERENCES users(id),
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memberships (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (story_id, user_id)
);

CREATE TABLE IF NOT EXISTS nodes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id       BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    parent_id      BIGINT REFERENCES nodes(id) ON DELETE CASCADE,
    node_type      VARCHAR(32) NOT NULL,
    title          TEXT NOT NULL,
    sort_order     INTEGER NOT NULL DEFAULT 0,
    language       VARCHAR(16),
    status         VARCHAR(16) NOT NULL DEFAULT 'draft',
    body           JSONB,
    script         JSONB,
    meta           JSONB,
    version        BIGINT NOT NULL DEFAULT 1,
    last_change_id VARCHAR(64),
    created_by     BIGINT NOT NULL,
    updated_by     BIGINT NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_nodes_story_parent ON nodes (story_id, parent_id);

CREATE TABLE IF NOT EXISTS characters (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    name       VARCHAR(255) NOT NULL,
    attributes JSONB,
    bio        TEXT,
    notes      TEXT,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lore_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    title      VARCHAR(255) NOT NULL,
    category   VARCHAR(255),
    body       TEXT,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS links (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    from_type  VARCHAR(32) NOT NULL,
    from_id    BIGINT NOT NULL,
    to_type    VARCHAR(32) NOT NULL,
    to_id      BIGINT NOT NULL,
    kind       VARCHAR(32) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS releases (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id     BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    version      INT NOT NULL,
    name         VARCHAR(255) NOT NULL,
    notes        TEXT,
    created_by   BIGINT NOT NULL,
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nodes        JSONB NOT NULL,
    UNIQUE (story_id, version)
);

-- Explicit writer checkpoints: a named snapshot of a node's authoring payloads
-- (title/body/script/meta) pinned to the node.version it captured. The revision
-- seam decision #6 (Release snapshot) uses these as version-pinned anchors.
CREATE TABLE IF NOT EXISTS node_checkpoints (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id      BIGINT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    node_version BIGINT NOT NULL,
    title        TEXT NOT NULL,
    body         JSONB,
    script       JSONB,
    meta         JSONB,
    note         TEXT,
    created_by   BIGINT NOT NULL REFERENCES users(id),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_node_checkpoints_node ON node_checkpoints (node_id, id);